In [3]:
# import libraries
import pandas as pd

# load the datasets
google_df = pd.read_csv('googleplaystore.csv', low_memory=False)
# and the ratings
google_ratings = pd.read_csv('googleplaystore_user_reviews.csv', low_memory=False)

# quick preview
google_df.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [4]:
# preview ratings
google_ratings.head(5)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [12]:
google_df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [19]:
google_df1 = google_df[google_df['Rating'] < 6]

In [20]:
google_df1.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [5]:
# 
google_df['Rating'].value_counts(bins = 10).sort_index()

(0.981, 2.8]     242
(2.8, 4.6]      8030
(4.6, 6.4]      1094
(6.4, 8.2]         0
(8.2, 10.0]        0
(10.0, 11.8]       0
(11.8, 13.6]       0
(13.6, 15.4]       0
(15.4, 17.2]       0
(17.2, 19.0]       1
Name: Rating, dtype: int64

In [21]:
google_df1['Rating'].value_counts(bins = 10).sort_index()

(0.995, 1.4]      20
(1.4, 1.8]        23
(1.8, 2.2]        47
(2.2, 2.6]        85
(2.6, 3.0]       195
(3.0, 3.4]       363
(3.4, 3.8]       879
(3.8, 4.2]      2614
(4.2, 4.6]      4046
(4.6, 5.0]      1094
Name: Rating, dtype: int64

In [8]:
# calculate average
avg_rating_df = google_df[['App', 'Rating']].groupby(['App']).mean()
avg_rating_df = avg_rating_df.sort_values('Rating', ascending=False)
avg_rating_df.head(10)

                                                Rating
App
Life Made WI-Fi Touchscreen Photo Frame           19.0
AJ Rafael Music Lessons                            5.0
Victoria EC                                        5.0
Cloud DX Connected Health                          5.0
CJ Gospel Hour                                     5.0
EB Scanner                                         5.0
FK CLASSIC FOR YOU                                 5.0
EB Cash Collections                                5.0
NOMISMA.com.cy by FMW                              5.0
Bacterial vaginosis Treatment - Sexual disease     5.0

In [22]:
# calculate average
avg_rating_df1 = google_df1[['App', 'Rating']].groupby(['App']).mean()
avg_rating_df1 = avg_rating_df1.sort_values('Rating', ascending=False)
avg_rating_df1.head(10)

                                                Rating
App
AJ Rafael Music Lessons                            5.0
EC Calgary                                         5.0
Cloud DX Connected Health                          5.0
EB Scanner                                         5.0
CJ Gospel Hour                                     5.0
FK CLASSIC FOR YOU                                 5.0
EB Cash Collections                                5.0
NOMISMA.com.cy by FMW                              5.0
Bacterial vaginosis Treatment - Sexual disease     5.0
Victoria EC                                        5.0

In [14]:
# calculate average with count
avg_rating_df = google_df.groupby(['App'])['Rating'].agg(['mean', 'count'])
avg_rating_df.rename(columns={'mean': 'vote_average', 'count': 'vote_count'}, inplace=True)
avg_rating_df.sort_values('vote_average', ascending=False).head(10)

                                                vote_average  vote_count
App
Life Made WI-Fi Touchscreen Photo Frame                 19.0           1
AJ Rafael Music Lessons                                  5.0           1
Victoria EC                                              5.0           1
Cloud DX Connected Health                                5.0           1
CJ Gospel Hour                                           5.0           1
EB Scanner                                               5.0           1
FK CLASSIC FOR YOU                                       5.0           1
EB Cash Collections                                      5.0           1
NOMISMA.com.cy by FMW                                    5.0           1
Bacterial vaginosis Treatment - Sexual disease           5.0           1

In [23]:
# calculate average with count
avg_rating_df1 = google_df1.groupby(['App'])['Rating'].agg(['mean', 'count'])
avg_rating_df1.rename(columns={'mean': 'vote_average', 'count': 'vote_count'}, inplace=True)
avg_rating_df1.sort_values('vote_average', ascending=False).head(10)

                                                vote_average  vote_count
App
AJ Rafael Music Lessons                                  5.0           1
EC Calgary                                               5.0           1
Cloud DX Connected Health                                5.0           1
EB Scanner                                               5.0           1
CJ Gospel Hour                                           5.0           1
FK CLASSIC FOR YOU                                       5.0           1
EB Cash Collections                                      5.0           1
NOMISMA.com.cy by FMW                                    5.0           1
Bacterial vaginosis Treatment - Sexual disease           5.0           1
Victoria EC                                              5.0           1

In [15]:
# C is the mean vote or rating across the whole dataframe
C = avg_rating_df['vote_average'].mean()

# m is the minimum votes or ratings to be listed
m = avg_rating_df['vote_count'].quantile(0.90)
m

# new data frame (redundant)
q_google = avg_rating_df.copy().loc[avg_rating_df['vote_count'] > m]
q_google.head(5)

                              vote_average  vote_count
App
10 Best Foods for You                  4.0           2
1800 Contacts - Lens Store             4.7           2
2017 EMRA Antibiotic Guide             4.4           2
21-Day Meditation Experience           4.4           2
365Scores - Live Scores                4.6           2

In [25]:
# C is the mean vote or rating across the whole dataframe
C1 = avg_rating_df1['vote_average'].mean()

# m is the minimum votes or ratings to be listed
m1 = avg_rating_df1['vote_count'].quantile(0.90)
m1

# new data frame (redundant)
q_google1 = avg_rating_df1.copy().loc[avg_rating_df1['vote_count'] > m1]
q_google1.head(5)

                              vote_average  vote_count
App
10 Best Foods for You                  4.0           2
1800 Contacts - Lens Store             4.7           2
2017 EMRA Antibiotic Guide             4.4           2
21-Day Meditation Experience           4.4           2
365Scores - Live Scores                4.6           2

In [16]:
q_google.tail(5)

                                                    vote_average  vote_count
App
stranger chat - anonymous chat                               3.5           2
textPlus: Free Text & Calls                                  4.1           2
theScore: Live Sports Scores, News, Stats & Videos           4.4           5
trivago: Hotels & Travel                                     4.2           3
wetter.com - Weather and Radar                               4.2           2

In [17]:
# weight function
def weighted_rating(x, m=m, C=C):
    v = x['vote_count']
    R = x['vote_average']
    return (v/(v+m) * R) + (m/(m+v) * C)

In [26]:
# weight function
def weighted_rating(x, m1=m1, C1=C1):
    v1 = x['vote_count']
    R1 = x['vote_average']
    return (v1/(v1+m1) * R1) + (m1/(m1+v1) * C1)

In [18]:
# check the new scores
avg_rating_df2 = avg_rating_df.copy().loc[avg_rating_df['vote_count'] >= m]
avg_rating_df2['score'] = avg_rating_df2.apply(weighted_rating, axis=1)
avg_rating_df2.sort_values('score', ascending=False).head(10)

,vote_average,vote_count,score
App,,,
Life Made WI-Fi Touchscreen Photo Frame,19.0,1,11.587535
420 BZ Budeze Delivery,5.0,2,4.725023
Sway Medical,5.0,2,4.725023
BP Journal - Blood Pressure Diary,5.0,2,4.725023
Wordscapes,4.8,4,4.675014
Six Pack in 30 Days - Abs Workout,4.9,2,4.658356
Duolingo: Learn Languages Free,4.7,7,4.634384
Zombie Catchers,4.7,6,4.625010
Bowmasters,4.7,6,4.625010
"Learn languages, grammar & vocabulary with Memrise",4.7,4,4.595014

In [ ]:
# check the new scores
avg_rating_df2 = avg_rating_df.copy().loc[avg_rating_df['vote_count'] >= m]
avg_rating_df2['score'] = avg_rating_df2.apply(weighted_rating, axis=1)
avg_rating_df2.sort_values('score', ascending=False).head(10)